# Generated by Django 4.2.1 on 2023-09-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoomApp', '0002_eventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='conference_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ConferenceRoomApp.conferenceroom'),
        ),
    ]
