# Generated by Django 4.2.1 on 2023-09-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoomApp', '0003_booking_conference_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chair_count',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
