# Generated by Django 4.2.5 on 2023-09-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoomApp', '0004_booking_chair_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='overlapping_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overlapping_requests', to='ConferenceRoomApp.booking'),
        ),
    ]
