# Generated by Django 4.2.5 on 2023-09-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoomApp', '0005_eventrequest_overlapping_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='overlapping_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overlapping_request', to='ConferenceRoomApp.booking'),
        ),
    ]
